# Netlify configuration for Meno.i frontend deployment

[build]
  # Build command for Next.js
  command = "cd packages/frontend && npm install && npm run build"

  # Output directory for Next.js (using Next.js runtime)
  publish = "packages/frontend/.next"

  # Base directory
  base = "/"

[build.environment]
  # Node version
  NODE_VERSION = "18.17.0"
  # Enable Next.js on Netlify
  NEXT_PRIVATE_TARGET = "server"

# Use Next.js Runtime plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Allow microphone for voice features, block camera and geolocation
    Permissions-Policy = "geolocation=(), camera=(), microphone=(self)"

# Cache static assets for better performance
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
