# Render deploy configuration for the Express API

services:
  - type: web
    name: menoai-api
    env: node
    plan: starter
    region: frankfurt
    buildCommand: pnpm install && pnpm --filter @meno/api build
    startCommand: pnpm --filter @meno/api start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://your-netlify-site.netlify.app"
      - key: SENTRY_DSN
        sync: false
      - key: OPENAI_API_KEY
        sync: false

